server.port=8081
spring.application.name=polaris-backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/polaris_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Configuration
polaris.jwt.secret=ZjRkMjQ4ZGUtOGYxNy00YjA5LWI2ZmEtNjcxZTlhYjVhNDgzLXBvbGFyaXMtYWktbGVhcm5pbmctcGxhdGZvcm0tc2VjcmV0LWtleS0yMDI2
polaris.jwt.expiration=86400000

# Groq AI Configuration
groq.api.key=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
groq.base.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
